export const data = {
  status: "success",
  records: [
    {
      resource_type: "user",
      shortname: "dmart",
      branch_name: "master",
      subpath: "users",
      attributes: {
        email: "new@email.coom",
        displayname: {
          en: "DMART (admin)",
          ar: "dfgddf",
          kd: "",
        },
        msisdn: "7112111432",
        payload: {
          content_type: "json",
          schema_shortname: "admin_profile",
          body: {
            department: "technical_support",
            sales_id: "",
            alternative_msisdn: "",
            governorate_shortnames: [],
          },
          last_validated: "2023-01-03T07:49:15.972200",
          validation_status: "valid",
        },
        type: "web",
        is_email_verified: true,
        is_msisdn_verified: true,
        force_password_change: false,
      },
      attachments: {
        media: [
          {
            resource_type: "media",
            uuid: "97936be2-58f2-4f6d-9412-63ef6c4b557c",
            shortname: "avatar",
            branch_name: "master",
            subpath: "users/dmart",
            attributes: {
              is_active: false,
              tags: [],
              created_at: "2022-11-14T15:22:36.011421",
              updated_at: "2022-11-14T15:22:36.011426",
              owner_shortname: "dmart",
              payload: {
                content_type: "image",
                checksum: "9a90293e8db0ea5f68378071aace476a0ff6d449",
                body: "avatar.png",
              },
            },
          },
        ],
      },
      permissions: {
        "ordering:collections:comment": {
          allowed_actions: ["query", "view"],
          conditions: ["is_active"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:collections:folder": {
          allowed_actions: ["query", "view"],
          conditions: ["is_active"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:collections:history": {
          allowed_actions: ["query", "view"],
          conditions: ["is_active"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:collections:content": {
          allowed_actions: ["query", "view"],
          conditions: ["is_active"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:collections:media": {
          allowed_actions: ["query", "view"],
          conditions: ["is_active"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:collections:permission": {
          allowed_actions: ["query", "view"],
          conditions: ["is_active"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:comment": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:relationship": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:ticket": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:content": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:media": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:alteration": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:json": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/public:locator": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:comment": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:ticket": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:content": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:media": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:alteration": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:json": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/inbox:locator": {
          allowed_actions: ["create"],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:comment": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:relationship": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:role": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:folder": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:history": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:space": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:user": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:ticket": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:content": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:group": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:media": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:alteration": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:json": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:permission": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:locator": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:acl": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/__all_subpaths__/protected:schema": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:schema:history": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:schema:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:schema:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:schema:history": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:schema:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:schema:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:schema:history": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:schema:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:schema:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:workflows:content": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:workflows:content": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:comment": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:relationship": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:role": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:folder": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:history": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:space": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:user": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:ticket": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:content": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:group": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:media": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:notification": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:alteration": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:json": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:permission": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:locator": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:acl": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/public:schema": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:comment": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:relationship": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:role": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:folder": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:history": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:space": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:user": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:ticket": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:content": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:group": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:media": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:notification": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:alteration": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:json": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:permission": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:locator": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:acl": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/inbox:schema": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:comment": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:relationship": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:role": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:folder": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:history": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:space": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:user": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:ticket": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:content": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:group": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:media": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:notification": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:alteration": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:json": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:permission": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:locator": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:acl": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/private:schema": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:comment": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:relationship": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:role": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:folder": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:history": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:space": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:user": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:ticket": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:content": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:group": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:media": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:notification": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:alteration": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:json": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:permission": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:locator": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:acl": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:people/dmart/protected:schema": {
          allowed_actions: ["delete", "create", "view", "query", "update"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "__all_spaces__:__all_subpaths__:folder": {
          allowed_actions: ["view", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "__all_spaces__:__all_subpaths__:space": {
          allowed_actions: ["delete", "update", "create", "query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:comment": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:relationship": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:role": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:history": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:space": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:user": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:ticket": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:content": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:group": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:media": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:json": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:notification": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:permission": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:locator": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:acl": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:/:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:comment": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:relationship": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:role": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:history": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:space": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:user": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:ticket": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:content": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:group": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:media": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:json": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:notification": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:permission": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:locator": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:acl": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:/:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:comment": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:relationship": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:role": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:history": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:space": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:user": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:ticket": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:content": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:group": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:media": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:json": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:notification": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:permission": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:locator": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:acl": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:/:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:comment": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:relationship": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:role": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:history": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:space": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:user": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:ticket": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:content": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:group": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:media": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:json": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:notification": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:permission": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:locator": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:acl": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "personal:/:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:comment": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:relationship": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:role": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:history": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:space": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:user": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:ticket": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:content": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:group": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:media": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:alteration": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:json": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:notification": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:permission": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:locator": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:acl": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:/:schema": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "test:schema:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:schema:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:schema:folder": {
          allowed_actions: [
            "delete",
            "create",
            "view",
            "query",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:products:content": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:products:media": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:users:content": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {
            "payload.schema_shortname": ["salesrep_profile"],
            roles: [["sales_rep"]],
          },
        },
        "management:users:media": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {
            "payload.schema_shortname": ["salesrep_profile"],
            roles: [["sales_rep"]],
          },
        },
        "management:users:user": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {
            roles: [
              [
                "distributor_admin",
                "channel_owner",
                "ros",
                "franchise",
                "d2d_promoter",
                "voucher_pos",
                "activating_pos",
                "zain_hq",
              ],
            ],
          },
        },
        "management:collections:content": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {
            "payload.schema_shortname": ["salesrep_profile"],
            roles: [["sales_rep"]],
          },
        },
        "management:collections:media": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {
            "payload.schema_shortname": ["salesrep_profile"],
            roles: [["sales_rep"]],
          },
        },
        "management:collections:user": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: ["own"],
          restricted_fields: [],
          allowed_fields_values: {
            "payload.schema_shortname": ["salesrep_profile"],
            roles: [["sales_rep"]],
          },
        },
        "management:order_allocation:content": {
          allowed_actions: [
            "delete",
            "create",
            "query",
            "view",
            "update",
            "attach",
          ],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:orders:ticket": {
          allowed_actions: ["view", "update", "attach", "query"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:roles:group": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:roles:role": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:groups:group": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "management:groups:role": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "ordering:orders:media": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:reports:content": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:reports:ticket": {
          allowed_actions: ["query", "view"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/change_ownership:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/change_ownership:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/sim_swap:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/sim_swap:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/correct_info:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/correct_info:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/postpaid_prime:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/postpaid_prime:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/add_remove_vas:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/add_remove_vas:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/dummy:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/dummy:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/rc_compensation:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/rc_compensation:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/check_info:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/check_info:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/migration:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/migration:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/connect_disconnect:media": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
        "aftersales:tickets/connect_disconnect:ticket": {
          allowed_actions: ["query", "view", "update", "attach"],
          conditions: [],
          restricted_fields: [],
          allowed_fields_values: {},
        },
      },
      roles: ["zain_hq", "admin", "distributor_admin"],
      groups: [],
    },
  ],
};
