"""adding UserPermissionsCache

Revision ID: 2338186ee676
Revises: 10d2041b94d4
Create Date: 2026-02-23 03:56:39.144503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2338186ee676'
down_revision: Union[str, None] = '10d2041b94d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpermissionscache',
    sa.Column('user_shortname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_shortname')
    )
    op.drop_table('authz_mv_meta', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authz_mv_meta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_source_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('authz_mv_meta_pkey'))
    )
    op.drop_table('userpermissionscache')
    # ### end Alembic commands ###
