"""rm ActiveSession table

Revision ID: 7520a89a8467
Revises: b53f916b3f6d
Create Date: 2024-12-26 09:28:12.717308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7520a89a8467'
down_revision: Union[str, None] = 'b53f916b3f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activesessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activesessions',
    sa.Column('shortname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='activesessions_pkey'),
    sa.UniqueConstraint('shortname', name='activesessions_shortname_key')
    )
    # ### end Alembic commands ###
